// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyorszdkbtxosrsdqzmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5b3JzemRrYnR4b3Nyc2Rxem11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzM0NjgsImV4cCI6MjA2NzQ0OTQ2OH0.C49ZAWuUNU3_M9wsUEJVTPMddZ-bbwABMm1b5J4fM0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});